// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	ride "github.com/muzfr7/fare_estimator/app/domain/ride"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Estimate provides a mock function with given fields: rideChan
func (_m *Service) Estimate(rideChan <-chan ride.Ride) <-chan []string {
	ret := _m.Called(rideChan)

	var r0 <-chan []string
	if rf, ok := ret.Get(0).(func(<-chan ride.Ride) <-chan []string); ok {
		r0 = rf(rideChan)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan []string)
		}
	}

	return r0
}
