// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

// Read provides a mock function with given fields: filePath
func (_m *Reader) Read(filePath string) (<-chan []string, <-chan error, error) {
	ret := _m.Called(filePath)

	var r0 <-chan []string
	if rf, ok := ret.Get(0).(func(string) <-chan []string); ok {
		r0 = rf(filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan []string)
		}
	}

	var r1 <-chan error
	if rf, ok := ret.Get(1).(func(string) <-chan error); ok {
		r1 = rf(filePath)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(filePath)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
