// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Writer is an autogenerated mock type for the Writer type
type Writer struct {
	mock.Mock
}

// Write provides a mock function with given fields: in
func (_m *Writer) Write(in <-chan []string) (<-chan int, <-chan error, error) {
	ret := _m.Called(in)

	var r0 <-chan int
	if rf, ok := ret.Get(0).(func(<-chan []string) <-chan int); ok {
		r0 = rf(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan int)
		}
	}

	var r1 <-chan error
	if rf, ok := ret.Get(1).(func(<-chan []string) <-chan error); ok {
		r1 = rf(in)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(<-chan []string) error); ok {
		r2 = rf(in)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
