// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	path "github.com/muzfr7/fare_estimator/app/domain/path"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CalculateDistance provides a mock function with given fields: startPath, endPath
func (_m *Service) CalculateDistance(startPath path.Path, endPath path.Path) float64 {
	ret := _m.Called(startPath, endPath)

	var r0 float64
	if rf, ok := ret.Get(0).(func(path.Path, path.Path) float64); ok {
		r0 = rf(startPath, endPath)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}
