// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	ride "github.com/muzfr7/fare_estimator/app/domain/ride"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: dataChan
func (_m *Service) Create(dataChan <-chan []string) (<-chan ride.Ride, <-chan error) {
	ret := _m.Called(dataChan)

	var r0 <-chan ride.Ride
	if rf, ok := ret.Get(0).(func(<-chan []string) <-chan ride.Ride); ok {
		r0 = rf(dataChan)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan ride.Ride)
		}
	}

	var r1 <-chan error
	if rf, ok := ret.Get(1).(func(<-chan []string) <-chan error); ok {
		r1 = rf(dataChan)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}

	return r0, r1
}
